# Generated by Django 4.0.1 on 2022-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_autologintoken_alter_tempuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
