# Generated by Django 4.0.1 on 2022-06-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_tempuser_password_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40, unique=True)),
                ('acounttype', models.CharField(choices=[('Estate', 'estate'), ('Supplier', 'supplier'), ('Feildowner', 'feildowner'), ('Null', 'null')], default='Null', max_length=10)),
                ('license', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='uuid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
