# Generated by Django 4.0.1 on 2022-06-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_licence_users_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='autologintoken',
            name='userid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
